# Generated by Django 5.2.3 on 2025-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usecase_delete_category_delete_favorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=20)),
                ('extension', models.CharField(max_length=10)),
                ('original_drop_date', models.DateField()),
                ('archived_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionDropInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=10, unique=True)),
                ('first_check_delay_hours', models.PositiveIntegerField(default=2)),
                ('second_check_delay_hours', models.PositiveIntegerField(default=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='name',
            name='use_cases',
        ),
        migrations.AlterField(
            model_name='name',
            name='competition',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='domain_list',
            field=models.CharField(choices=[('all_list', 'All List'), ('pending_delete', 'Pending Delete'), ('deleted', 'Deleted'), ('marketplace', 'Marketplace')], default='pending_delete', max_length=50),
        ),
        migrations.AlterField(
            model_name='name',
            name='drop_date',
            field=models.DateField(help_text='Set manually in loader per batch'),
        ),
        migrations.AlterField(
            model_name='name',
            name='drop_time',
            field=models.DateTimeField(editable=False, help_text='Auto-computed in save() based on extension'),
        ),
        migrations.AlterField(
            model_name='name',
            name='extension',
            field=models.CharField(choices=[('all_extensions', 'All_extensions'), ('com', 'Com'), ('co', 'Co'), ('io', 'Io'), ('ai', 'Ai')], editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='name',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('taken', 'Taken'), ('unverified', 'Unverified')], default='pending', max_length=20),
        ),
    ]
