# Generated by Django 5.2.3 on 2025-06-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_archivedname_extensiondropinfo_remove_name_use_cases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='name',
            name='top_rated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='acquired',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_names',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
