# Generated by Django 5.2.3 on 2025-06-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
