# Generated by Django 5.2.3 on 2025-06-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_favorite'),
    ]

    
    operations = [
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX user_email_unique_idx
                ON auth_user (LOWER(email))
                WHERE email IS NOT NULL;
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS user_email_unique_idx;
            """
        )
    ]