# Generated by Django 5.2.4 on 2025-07-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_newsletter_publicinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicinquiry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
