# Generated by Django 5.2.4 on 2025-07-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_publicinquiry_ip_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usecase',
            unique_together={('domain_name', 'order')},
        ),
        migrations.AddField(
            model_name='usecase',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='target_market',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='usecase',
            unique_together={('domain_name', 'order'), ('domain_name', 'slug')},
        ),
    ]
