# Generated by Django 5.2.4 on 2025-07-16 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usecase_unique_together_usecase_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='SaaS viability score (1–10), determined by the LLM', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
