# Generated by Django 5.2.4 on 2025-07-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_name_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='case_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='target_market',
            field=models.CharField(max_length=100),
        ),
    ]
