# Generated by Django 5.2.4 on 2025-07-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_usecase_case_title_alter_usecase_target_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namecategory',
            name='name',
            field=models.CharField(choices=[('health_and_wellness', 'Health_And_Wellness'), ('tech', 'Tech')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='nametag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
