# Generated by Django 5.2.4 on 2025-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_namecategory_name_alter_nametag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
