# Generated by Django 5.2.4 on 2025-07-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_namecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='is_idea_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
