# Generated by Django 5.2.4 on 2025-07-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_name_is_idea_of_the_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='competition',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20),
        ),
    ]
