# Generated by Django 5.2.4 on 2025-07-17 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_usecase_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquirednames',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name'),
        ),
        migrations.AlterField(
            model_name='savednames',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name'),
        ),
        migrations.AlterUniqueTogether(
            name='acquirednames',
            unique_together={('user', 'name')},
        ),
    ]
