# Generated by Django 5.2.4 on 2025-07-17 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_acquirednames_name_alter_savednames_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savednames',
            unique_together={('user', 'name')},
        ),
    ]
