# Generated by Django 5.2.4 on 2025-07-17 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_savednames_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcquiredNames',
            new_name='AcquiredName',
        ),
        migrations.RenameModel(
            old_name='SavedNames',
            new_name='SavedName',
        ),
    ]
