# Generated by Django 5.2.4 on 2025-07-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_acquirednames_acquiredname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='domain_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
