# Generated by Django 5.2.4 on 2025-07-23 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_name_domain_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NameCategory',
            new_name='UseCaseCategory',
        ),
        migrations.RenameModel(
            old_name='NameTag',
            new_name='UseCaseTag',
        ),
        migrations.AlterModelOptions(
            name='usecase',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='name',
            name='category',
        ),
        migrations.RemoveField(
            model_name='name',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='name',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='name',
            name='tag',
        ),
        migrations.AddField(
            model_name='usecase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usecasecategory'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usecase',
            name='tag',
            field=models.ManyToManyField(blank=True, to='api.usecasetag'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='domain_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases_domain_name', to='api.name'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100),
        ),
    ]
