# Generated by Django 5.2.4 on 2025-07-23 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_namecategory_usecasecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecasecategory',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usecase',
            name='domain_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='api.name'),
        ),
    ]
