# Generated by Django 5.2.4 on 2025-07-23 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_usecasecategory_slug_alter_usecase_domain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='category',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, to='api.usecasecategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usecase',
            name='tag',
            field=models.ManyToManyField(to='api.usecasetag'),
        ),
    ]
