# Generated by Django 5.2.4 on 2025-07-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_usecase_competition_alter_usecase_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='competition',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='revenue_potential',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=100),
        ),
    ]
