# Generated by Django 5.2.4 on 2025-08-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_usecase_competition_alter_usecase_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('category', models.CharField(choices=[('pending', 'Pending Delete'), ('deleted', 'Deleted')], max_length=20)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usecase')),
            ],
            options={
                'unique_together': {('date', 'category')},
            },
        ),
    ]
