# Generated by Django 5.2.4 on 2025-08-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_new_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ideaoftheday',
            unique_together={('drop_date', 'domain_list')},
        ),
        migrations.AlterField(
            model_name='ideaoftheday',
            name='domain_list',
            field=models.CharField(choices=[('all_list', 'All List'), ('pending_delete', 'Pending Delete'), ('deleted', 'Deleted'), ('marketplace', 'Marketplace')], default='pending_delete', max_length=50),
        ),
        migrations.AlterField(
            model_name='ideaoftheday',
            name='drop_date',
            field=models.DateField(default='2025-08-08'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ideaoftheday',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ideaoftheday',
            name='date',
        ),
    ]
