# Generated by Django 5.2.4 on 2025-08-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_ideaoftheday_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processing_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('celery', 'Auto')], default='manual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['processed'], name='api_uploade_process_c44e7a_idx'),
        ),
    ]
