# Generated by Django 5.2.4 on 2025-08-10 14:30

from django.db import migrations, models


def mark_existing_top_rated(apps, schema_editor):
    Name = apps.get_model('api', 'Name')
    Name.objects.filter(score__gte=7).update(
        is_top_rated=True,
        top_rated_date=models.F('drop_date')  # Use drop_date as the rating date
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_uploadedfile_processed_at_and_more'),
    ]

    operations = [
        migrations.RunPython(mark_existing_top_rated),
    ]
