# Generated by Django 5.2.4 on 2025-08-10 14:44

from django.db import migrations, models
from django.conf import settings



def update_top_rated(apps, schema_editor):
    Name = apps.get_model('api', 'Name')
    Name.objects.filter(score__gte=settings.TOP_RATED_THRESHOLD).update(
        is_top_rated=True,
        top_rated_date=models.F('drop_date')
    )
    Name.objects.filter(
        score__lt=settings.TOP_RATED_THRESHOLD
    ).update(is_top_rated=False)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_mark_existing_top_rated'),
    ]

    operations = [
        migrations.RunPython(update_top_rated)
    ]
