# Generated by Django 5.2.4 on 2025-08-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_update_top_rated_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='domain_list',
            field=models.CharField(choices=[('all_list', 'All List'), ('pending_delete', 'Pending Delete'), ('deleted', 'Deleted'), ('marketplace', 'Marketplace')], db_index=True, default='pending_delete', max_length=50),
        ),
        migrations.AlterField(
            model_name='name',
            name='drop_date',
            field=models.DateField(db_index=True, help_text='Set manually in loader per batch'),
        ),
        migrations.AlterField(
            model_name='name',
            name='drop_time',
            field=models.DateTimeField(db_index=True, editable=False, help_text='Auto-computed in save() based on extension'),
        ),
        migrations.AlterField(
            model_name='name',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('taken', 'Taken'), ('unverified', 'Unverified')], db_index=True, default='pending', max_length=20),
        ),
    ]
