# Generated by Django 5.2.4 on 2025-08-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_name_domain_list_alter_name_drop_date_and_more'),
    ]


    operations = [
        migrations.RunSQL(
            """
            -- Drop tables with CASCADE to handle dependencies
            DROP TABLE IF EXISTS account_emailconfirmation CASCADE;
            DROP TABLE IF EXISTS account_emailaddress CASCADE;
            DROP TABLE IF EXISTS socialaccount_socialtoken CASCADE;
            DROP TABLE IF EXISTS socialaccount_socialaccount CASCADE;
            DROP TABLE IF EXISTS socialaccount_socialapp CASCADE;
            DROP TABLE IF EXISTS authtoken_token CASCADE;
            """,
            
            reverse_sql="""
            -- Recreate tables with minimal schema (order matters for FKs)
            CREATE TABLE account_emailaddress (
                id SERIAL PRIMARY KEY,
                email VARCHAR(254) NOT NULL,
                verified BOOLEAN NOT NULL,
                "primary" BOOLEAN NOT NULL,
                user_id INTEGER NOT NULL
            );
            
            CREATE TABLE account_emailconfirmation (
                id SERIAL PRIMARY KEY,
                created TIMESTAMP NOT NULL,
                sent TIMESTAMP NULL,
                key VARCHAR(64) NOT NULL,
                email_address_id INTEGER NOT NULL REFERENCES account_emailaddress(id)
            );
            
            CREATE TABLE authtoken_token (
                key VARCHAR(40) NOT NULL PRIMARY KEY,
                created TIMESTAMP NOT NULL,
                user_id INTEGER NOT NULL UNIQUE
            );
            """
        )
    ]