# Generated by Django 5.2.4 on 2025-08-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_auth_tables'),
    ]

   
    operations = [
        migrations.RunSQL(
            """
            -- Drop socialaccount tables with CASCADE
            DROP TABLE IF EXISTS socialaccount_socialtoken CASCADE;
            DROP TABLE IF EXISTS socialaccount_socialaccount CASCADE;
            DROP TABLE IF EXISTS socialaccount_socialapp CASCADE;
            """,
            
            reverse_sql="""
            -- Recreation SQL (for rollback capability)
            CREATE TABLE socialaccount_socialapp (
                id SERIAL PRIMARY KEY,
                provider VARCHAR(30) NOT NULL,
                name VARCHAR(40) NOT NULL,
                client_id VARCHAR(191) NOT NULL,
                secret VARCHAR(191) NOT NULL,
                key VARCHAR(191) NOT NULL
            );
            
            CREATE TABLE socialaccount_socialaccount (
                id SERIAL PRIMARY KEY,
                provider VARCHAR(30) NOT NULL,
                uid VARCHAR(191) NOT NULL,
                last_login TIMESTAMP NULL,
                date_joined TIMESTAMP NOT NULL,
                extra_data TEXT NOT NULL,
                user_id INTEGER NOT NULL REFERENCES auth_user(id)
            );
            
            CREATE TABLE socialaccount_socialtoken (
                id SERIAL PRIMARY KEY,
                token TEXT NOT NULL,
                token_secret TEXT NOT NULL,
                expires_at TIMESTAMP NULL,
                account_id INTEGER NOT NULL REFERENCES socialaccount_socialaccount(id),
                app_id INTEGER NOT NULL REFERENCES socialaccount_socialapp(id)
            );
            """
        )
    ]