# Generated by Django 5.2.4 on 2025-08-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_socialaccount_tables'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS socialaccount_socialapp_sites CASCADE;",
            reverse_sql="""
            CREATE TABLE socialaccount_socialapp_sites (
                id SERIAL PRIMARY KEY,
                socialapp_id INTEGER NOT NULL,
                site_id INTEGER NOT NULL REFERENCES django_site(id)
            );
            """
        )
    ]