# Generated by Django 5.2.5 on 2025-08-21 10:59

from django.db import migrations

def create_update_idea_task(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Schedule: Daily at 00:00 UTC
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="0",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="update_idea_of_the_day",
        defaults={
            "task": "api.tasks.update_idea_of_the_day",
            "crontab": schedule,
            "enabled": True,
            "expires": None,
        },
    )

def remove_update_idea_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name="update_idea_of_the_day").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_add_periodic_tasks'),
        ("django_celery_beat", "0016_alter_crontabschedule_timezone"),
    ]

    operations = [
        migrations.RunPython(create_update_idea_task, remove_update_idea_task),
    ]