# Generated by Django 5.2.5 on 2025-08-21 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_add_update_idea_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='domain_list',
            field=models.CharField(choices=[('pending_delete', 'Pending Delete'), ('deleted', 'Deleted'), ('marketplace', 'Marketplace'), ('all_list', 'All List')], default='pending_delete', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='drop_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
