# Generated by Django 5.2.5 on 2025-08-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20250828_0600'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS name_domain_name_pattern_idx
            ON api_name (domain_name varchar_pattern_ops);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS name_domain_name_pattern_idx;
            """
        ),
    ]
