# Generated by Django 5.2.5 on 2025-08-31 23:58

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_adding_dbindex_for_search'),
    ]


    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;",
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ideaoftheday',
            name='domain_list',
            field=models.CharField(
                choices=[
                    ('all_list', 'All List'),
                    ('pending_delete', 'Pending Delete'),
                    ('deleting_today', 'Deleting Today'),
                    ('deleted', 'Deleted'),
                    ('marketplace', 'Marketplace')
                ],
                default='pending_delete',
                max_length=50
            ),
        ),
        migrations.AlterField(
            model_name='name',
            name='domain_list',
            field=models.CharField(
                choices=[
                    ('all_list', 'All List'),
                    ('pending_delete', 'Pending Delete'),
                    ('deleting_today', 'Deleting Today'),
                    ('deleted', 'Deleted'),
                    ('marketplace', 'Marketplace')
                ],
                db_index=True,
                default='pending_delete',
                max_length=50
            ),
        ),
        migrations.AddIndex(
            model_name='usecase',
            index=models.Index(fields=['slug'], name='api_usecase_slug_838e71_idx'),
        ),
        migrations.AddIndex(
            model_name='usecase',
            index=models.Index(fields=['created_at'], name='api_usecase_created_660d81_idx'),
        ),
        migrations.AddIndex(
            model_name='usecase',
            index=models.Index(fields=['competition'], name='api_usecase_competi_81d84c_idx'),
        ),
        migrations.AddIndex(
            model_name='usecase',
            index=models.Index(fields=['difficulty'], name='api_usecase_difficu_9a4262_idx'),
        ),
        migrations.AddIndex(
            model_name='usecase',
            index=models.Index(fields=['category'], name='api_usecase_categor_f758dc_idx'),
        ),
        migrations.AddIndex(
            model_name='usecase',
            index=models.Index(fields=['target_market'], name='api_usecase_target__d91c14_idx'),
        ),
        migrations.AddIndex(
            model_name='usecase',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['target_market'],
                name='target_market_gin',
                opclasses=['gin_trgm_ops'],
            ),
        ),
    ]
