# Generated by Django 5.2.5 on 2025-09-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_appuser_is_active_appuser_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usecase',
            name='target_market_gin',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_login',
        ),
    ]
