# Generated by Django 5.2.5 on 2025-09-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_usecase_target_market_gin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='usecase',
            name='target_markets',
            field=models.ManyToManyField(blank=True, related_name='use_cases', to='api.targetmarket'),
        ),
    ]
