# Generated by Django 5.2.5 on 2025-09-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_populate_target_markets_from_charfield'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usecase',
            name='api_usecase_target__d91c14_idx',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='target_market',
        ),
    ]
