# Generated by Django 5.2.5 on 2025-09-08 06:07

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_old_target_market_charfield'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='targetmarket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='targetmarket_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
