# Generated by Django 5.2.5 on 2025-09-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_targetmarket_targetmarket_name_gin_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='business_model',
            field=models.CharField(blank=True, choices=[('B2B', 'Business-to-Business'), ('B2C', 'Business-to-Consumer'), ('Prosumer', 'Prosumer')], db_index=True, help_text='The primary business model for this use case.', max_length=10, null=True),
        ),
    ]
